// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ComplexPublication.proto

package org.project.models;

public final class ProtoComplexPublication {
  private ProtoComplexPublication() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ComplexPublicationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ComplexPublication)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string uuid = 1;</code>
     * @return The uuid.
     */
    String getUuid();
    /**
     * <code>string uuid = 1;</code>
     * @return The bytes for uuid.
     */
    com.google.protobuf.ByteString
        getUuidBytes();

    /**
     * <code>string city = 2;</code>
     * @return The city.
     */
    String getCity();
    /**
     * <code>string city = 2;</code>
     * @return The bytes for city.
     */
    com.google.protobuf.ByteString
        getCityBytes();

    /**
     * <code>.Location location = 3;</code>
     * @return Whether the location field is set.
     */
    boolean hasLocation();
    /**
     * <code>.Location location = 3;</code>
     * @return The location.
     */
    Location getLocation();
    /**
     * <code>.Location location = 3;</code>
     */
    LocationOrBuilder getLocationOrBuilder();

    /**
     * <code>double avg_temperature = 4;</code>
     * @return The avgTemperature.
     */
    double getAvgTemperature();

    /**
     * <code>double avg_rain = 5;</code>
     * @return The avgRain.
     */
    double getAvgRain();

    /**
     * <code>double avg_wind = 6;</code>
     * @return The avgWind.
     */
    double getAvgWind();
  }
  /**
   * Protobuf type {@code ComplexPublication}
   */
  public static final class ComplexPublication extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ComplexPublication)
      ComplexPublicationOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ComplexPublication.newBuilder() to construct.
    private ComplexPublication(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ComplexPublication() {
      uuid_ = "";
      city_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new ComplexPublication();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtoComplexPublication.internal_static_ComplexPublication_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtoComplexPublication.internal_static_ComplexPublication_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ComplexPublication.class, Builder.class);
    }

    public static final int UUID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile Object uuid_ = "";
    /**
     * <code>string uuid = 1;</code>
     * @return The uuid.
     */
    @Override
    public String getUuid() {
      Object ref = uuid_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        uuid_ = s;
        return s;
      }
    }
    /**
     * <code>string uuid = 1;</code>
     * @return The bytes for uuid.
     */
    @Override
    public com.google.protobuf.ByteString
        getUuidBytes() {
      Object ref = uuid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        uuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CITY_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile Object city_ = "";
    /**
     * <code>string city = 2;</code>
     * @return The city.
     */
    @Override
    public String getCity() {
      Object ref = city_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        city_ = s;
        return s;
      }
    }
    /**
     * <code>string city = 2;</code>
     * @return The bytes for city.
     */
    @Override
    public com.google.protobuf.ByteString
        getCityBytes() {
      Object ref = city_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        city_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LOCATION_FIELD_NUMBER = 3;
    private Location location_;
    /**
     * <code>.Location location = 3;</code>
     * @return Whether the location field is set.
     */
    @Override
    public boolean hasLocation() {
      return location_ != null;
    }
    /**
     * <code>.Location location = 3;</code>
     * @return The location.
     */
    @Override
    public Location getLocation() {
      return location_ == null ? Location.getDefaultInstance() : location_;
    }
    /**
     * <code>.Location location = 3;</code>
     */
    @Override
    public LocationOrBuilder getLocationOrBuilder() {
      return location_ == null ? Location.getDefaultInstance() : location_;
    }

    public static final int AVG_TEMPERATURE_FIELD_NUMBER = 4;
    private double avgTemperature_ = 0D;
    /**
     * <code>double avg_temperature = 4;</code>
     * @return The avgTemperature.
     */
    @Override
    public double getAvgTemperature() {
      return avgTemperature_;
    }

    public static final int AVG_RAIN_FIELD_NUMBER = 5;
    private double avgRain_ = 0D;
    /**
     * <code>double avg_rain = 5;</code>
     * @return The avgRain.
     */
    @Override
    public double getAvgRain() {
      return avgRain_;
    }

    public static final int AVG_WIND_FIELD_NUMBER = 6;
    private double avgWind_ = 0D;
    /**
     * <code>double avg_wind = 6;</code>
     * @return The avgWind.
     */
    @Override
    public double getAvgWind() {
      return avgWind_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(uuid_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, uuid_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(city_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, city_);
      }
      if (location_ != null) {
        output.writeMessage(3, getLocation());
      }
      if (Double.doubleToRawLongBits(avgTemperature_) != 0) {
        output.writeDouble(4, avgTemperature_);
      }
      if (Double.doubleToRawLongBits(avgRain_) != 0) {
        output.writeDouble(5, avgRain_);
      }
      if (Double.doubleToRawLongBits(avgWind_) != 0) {
        output.writeDouble(6, avgWind_);
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(uuid_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, uuid_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(city_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, city_);
      }
      if (location_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getLocation());
      }
      if (Double.doubleToRawLongBits(avgTemperature_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, avgTemperature_);
      }
      if (Double.doubleToRawLongBits(avgRain_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(5, avgRain_);
      }
      if (Double.doubleToRawLongBits(avgWind_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(6, avgWind_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ComplexPublication)) {
        return super.equals(obj);
      }
      ComplexPublication other = (ComplexPublication) obj;

      if (!getUuid()
          .equals(other.getUuid())) return false;
      if (!getCity()
          .equals(other.getCity())) return false;
      if (hasLocation() != other.hasLocation()) return false;
      if (hasLocation()) {
        if (!getLocation()
            .equals(other.getLocation())) return false;
      }
      if (Double.doubleToLongBits(getAvgTemperature())
          != Double.doubleToLongBits(
              other.getAvgTemperature())) return false;
      if (Double.doubleToLongBits(getAvgRain())
          != Double.doubleToLongBits(
              other.getAvgRain())) return false;
      if (Double.doubleToLongBits(getAvgWind())
          != Double.doubleToLongBits(
              other.getAvgWind())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + UUID_FIELD_NUMBER;
      hash = (53 * hash) + getUuid().hashCode();
      hash = (37 * hash) + CITY_FIELD_NUMBER;
      hash = (53 * hash) + getCity().hashCode();
      if (hasLocation()) {
        hash = (37 * hash) + LOCATION_FIELD_NUMBER;
        hash = (53 * hash) + getLocation().hashCode();
      }
      hash = (37 * hash) + AVG_TEMPERATURE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          Double.doubleToLongBits(getAvgTemperature()));
      hash = (37 * hash) + AVG_RAIN_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          Double.doubleToLongBits(getAvgRain()));
      hash = (37 * hash) + AVG_WIND_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          Double.doubleToLongBits(getAvgWind()));
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ComplexPublication parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ComplexPublication parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ComplexPublication parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ComplexPublication parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ComplexPublication parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ComplexPublication parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ComplexPublication parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ComplexPublication parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ComplexPublication parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ComplexPublication parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ComplexPublication parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ComplexPublication parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ComplexPublication prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ComplexPublication}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ComplexPublication)
        ComplexPublicationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtoComplexPublication.internal_static_ComplexPublication_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtoComplexPublication.internal_static_ComplexPublication_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ComplexPublication.class, Builder.class);
      }

      // Construct using org.project.models.ProtoComplexPublication.ComplexPublication.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        uuid_ = "";
        city_ = "";
        location_ = null;
        if (locationBuilder_ != null) {
          locationBuilder_.dispose();
          locationBuilder_ = null;
        }
        avgTemperature_ = 0D;
        avgRain_ = 0D;
        avgWind_ = 0D;
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProtoComplexPublication.internal_static_ComplexPublication_descriptor;
      }

      @Override
      public ComplexPublication getDefaultInstanceForType() {
        return ComplexPublication.getDefaultInstance();
      }

      @Override
      public ComplexPublication build() {
        ComplexPublication result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public ComplexPublication buildPartial() {
        ComplexPublication result = new ComplexPublication(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(ComplexPublication result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.uuid_ = uuid_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.city_ = city_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.location_ = locationBuilder_ == null
              ? location_
              : locationBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.avgTemperature_ = avgTemperature_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.avgRain_ = avgRain_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.avgWind_ = avgWind_;
        }
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ComplexPublication) {
          return mergeFrom((ComplexPublication)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ComplexPublication other) {
        if (other == ComplexPublication.getDefaultInstance()) return this;
        if (!other.getUuid().isEmpty()) {
          uuid_ = other.uuid_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getCity().isEmpty()) {
          city_ = other.city_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.hasLocation()) {
          mergeLocation(other.getLocation());
        }
        if (other.getAvgTemperature() != 0D) {
          setAvgTemperature(other.getAvgTemperature());
        }
        if (other.getAvgRain() != 0D) {
          setAvgRain(other.getAvgRain());
        }
        if (other.getAvgWind() != 0D) {
          setAvgWind(other.getAvgWind());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                uuid_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                city_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                input.readMessage(
                    getLocationFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 33: {
                avgTemperature_ = input.readDouble();
                bitField0_ |= 0x00000008;
                break;
              } // case 33
              case 41: {
                avgRain_ = input.readDouble();
                bitField0_ |= 0x00000010;
                break;
              } // case 41
              case 49: {
                avgWind_ = input.readDouble();
                bitField0_ |= 0x00000020;
                break;
              } // case 49
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private Object uuid_ = "";
      /**
       * <code>string uuid = 1;</code>
       * @return The uuid.
       */
      public String getUuid() {
        Object ref = uuid_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          uuid_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string uuid = 1;</code>
       * @return The bytes for uuid.
       */
      public com.google.protobuf.ByteString
          getUuidBytes() {
        Object ref = uuid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          uuid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string uuid = 1;</code>
       * @param value The uuid to set.
       * @return This builder for chaining.
       */
      public Builder setUuid(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        uuid_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string uuid = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearUuid() {
        uuid_ = getDefaultInstance().getUuid();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string uuid = 1;</code>
       * @param value The bytes for uuid to set.
       * @return This builder for chaining.
       */
      public Builder setUuidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        uuid_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private Object city_ = "";
      /**
       * <code>string city = 2;</code>
       * @return The city.
       */
      public String getCity() {
        Object ref = city_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          city_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string city = 2;</code>
       * @return The bytes for city.
       */
      public com.google.protobuf.ByteString
          getCityBytes() {
        Object ref = city_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          city_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string city = 2;</code>
       * @param value The city to set.
       * @return This builder for chaining.
       */
      public Builder setCity(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        city_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string city = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCity() {
        city_ = getDefaultInstance().getCity();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string city = 2;</code>
       * @param value The bytes for city to set.
       * @return This builder for chaining.
       */
      public Builder setCityBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        city_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private Location location_;
      private com.google.protobuf.SingleFieldBuilderV3<
          Location, Location.Builder, LocationOrBuilder> locationBuilder_;
      /**
       * <code>.Location location = 3;</code>
       * @return Whether the location field is set.
       */
      public boolean hasLocation() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>.Location location = 3;</code>
       * @return The location.
       */
      public Location getLocation() {
        if (locationBuilder_ == null) {
          return location_ == null ? Location.getDefaultInstance() : location_;
        } else {
          return locationBuilder_.getMessage();
        }
      }
      /**
       * <code>.Location location = 3;</code>
       */
      public Builder setLocation(Location value) {
        if (locationBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          location_ = value;
        } else {
          locationBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>.Location location = 3;</code>
       */
      public Builder setLocation(
          Location.Builder builderForValue) {
        if (locationBuilder_ == null) {
          location_ = builderForValue.build();
        } else {
          locationBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>.Location location = 3;</code>
       */
      public Builder mergeLocation(Location value) {
        if (locationBuilder_ == null) {
          if (((bitField0_ & 0x00000004) != 0) &&
            location_ != null &&
            location_ != Location.getDefaultInstance()) {
            getLocationBuilder().mergeFrom(value);
          } else {
            location_ = value;
          }
        } else {
          locationBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>.Location location = 3;</code>
       */
      public Builder clearLocation() {
        bitField0_ = (bitField0_ & ~0x00000004);
        location_ = null;
        if (locationBuilder_ != null) {
          locationBuilder_.dispose();
          locationBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.Location location = 3;</code>
       */
      public Location.Builder getLocationBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getLocationFieldBuilder().getBuilder();
      }
      /**
       * <code>.Location location = 3;</code>
       */
      public LocationOrBuilder getLocationOrBuilder() {
        if (locationBuilder_ != null) {
          return locationBuilder_.getMessageOrBuilder();
        } else {
          return location_ == null ?
              Location.getDefaultInstance() : location_;
        }
      }
      /**
       * <code>.Location location = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Location, Location.Builder, LocationOrBuilder>
          getLocationFieldBuilder() {
        if (locationBuilder_ == null) {
          locationBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Location, Location.Builder, LocationOrBuilder>(
                  getLocation(),
                  getParentForChildren(),
                  isClean());
          location_ = null;
        }
        return locationBuilder_;
      }

      private double avgTemperature_ ;
      /**
       * <code>double avg_temperature = 4;</code>
       * @return The avgTemperature.
       */
      @Override
      public double getAvgTemperature() {
        return avgTemperature_;
      }
      /**
       * <code>double avg_temperature = 4;</code>
       * @param value The avgTemperature to set.
       * @return This builder for chaining.
       */
      public Builder setAvgTemperature(double value) {
        
        avgTemperature_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>double avg_temperature = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearAvgTemperature() {
        bitField0_ = (bitField0_ & ~0x00000008);
        avgTemperature_ = 0D;
        onChanged();
        return this;
      }

      private double avgRain_ ;
      /**
       * <code>double avg_rain = 5;</code>
       * @return The avgRain.
       */
      @Override
      public double getAvgRain() {
        return avgRain_;
      }
      /**
       * <code>double avg_rain = 5;</code>
       * @param value The avgRain to set.
       * @return This builder for chaining.
       */
      public Builder setAvgRain(double value) {
        
        avgRain_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>double avg_rain = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearAvgRain() {
        bitField0_ = (bitField0_ & ~0x00000010);
        avgRain_ = 0D;
        onChanged();
        return this;
      }

      private double avgWind_ ;
      /**
       * <code>double avg_wind = 6;</code>
       * @return The avgWind.
       */
      @Override
      public double getAvgWind() {
        return avgWind_;
      }
      /**
       * <code>double avg_wind = 6;</code>
       * @param value The avgWind to set.
       * @return This builder for chaining.
       */
      public Builder setAvgWind(double value) {
        
        avgWind_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>double avg_wind = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearAvgWind() {
        bitField0_ = (bitField0_ & ~0x00000020);
        avgWind_ = 0D;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ComplexPublication)
    }

    // @@protoc_insertion_point(class_scope:ComplexPublication)
    private static final ComplexPublication DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ComplexPublication();
    }

    public static ComplexPublication getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ComplexPublication>
        PARSER = new com.google.protobuf.AbstractParser<ComplexPublication>() {
      @Override
      public ComplexPublication parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ComplexPublication> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ComplexPublication> getParserForType() {
      return PARSER;
    }

    @Override
    public ComplexPublication getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface LocationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Location)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>double latitude = 1;</code>
     * @return The latitude.
     */
    double getLatitude();

    /**
     * <code>double longitude = 2;</code>
     * @return The longitude.
     */
    double getLongitude();
  }
  /**
   * Protobuf type {@code Location}
   */
  public static final class Location extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Location)
      LocationOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Location.newBuilder() to construct.
    private Location(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Location() {
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new Location();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtoComplexPublication.internal_static_Location_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtoComplexPublication.internal_static_Location_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Location.class, Builder.class);
    }

    public static final int LATITUDE_FIELD_NUMBER = 1;
    private double latitude_ = 0D;
    /**
     * <code>double latitude = 1;</code>
     * @return The latitude.
     */
    @Override
    public double getLatitude() {
      return latitude_;
    }

    public static final int LONGITUDE_FIELD_NUMBER = 2;
    private double longitude_ = 0D;
    /**
     * <code>double longitude = 2;</code>
     * @return The longitude.
     */
    @Override
    public double getLongitude() {
      return longitude_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (Double.doubleToRawLongBits(latitude_) != 0) {
        output.writeDouble(1, latitude_);
      }
      if (Double.doubleToRawLongBits(longitude_) != 0) {
        output.writeDouble(2, longitude_);
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (Double.doubleToRawLongBits(latitude_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, latitude_);
      }
      if (Double.doubleToRawLongBits(longitude_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, longitude_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Location)) {
        return super.equals(obj);
      }
      Location other = (Location) obj;

      if (Double.doubleToLongBits(getLatitude())
          != Double.doubleToLongBits(
              other.getLatitude())) return false;
      if (Double.doubleToLongBits(getLongitude())
          != Double.doubleToLongBits(
              other.getLongitude())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + LATITUDE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          Double.doubleToLongBits(getLatitude()));
      hash = (37 * hash) + LONGITUDE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          Double.doubleToLongBits(getLongitude()));
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Location parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Location parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Location parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Location parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Location parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Location parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Location parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Location parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Location parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Location parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Location parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Location parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Location prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Location}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Location)
        LocationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtoComplexPublication.internal_static_Location_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtoComplexPublication.internal_static_Location_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Location.class, Builder.class);
      }

      // Construct using org.project.models.ProtoComplexPublication.Location.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        latitude_ = 0D;
        longitude_ = 0D;
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProtoComplexPublication.internal_static_Location_descriptor;
      }

      @Override
      public Location getDefaultInstanceForType() {
        return Location.getDefaultInstance();
      }

      @Override
      public Location build() {
        Location result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Location buildPartial() {
        Location result = new Location(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(Location result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.latitude_ = latitude_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.longitude_ = longitude_;
        }
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Location) {
          return mergeFrom((Location)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Location other) {
        if (other == Location.getDefaultInstance()) return this;
        if (other.getLatitude() != 0D) {
          setLatitude(other.getLatitude());
        }
        if (other.getLongitude() != 0D) {
          setLongitude(other.getLongitude());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 9: {
                latitude_ = input.readDouble();
                bitField0_ |= 0x00000001;
                break;
              } // case 9
              case 17: {
                longitude_ = input.readDouble();
                bitField0_ |= 0x00000002;
                break;
              } // case 17
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private double latitude_ ;
      /**
       * <code>double latitude = 1;</code>
       * @return The latitude.
       */
      @Override
      public double getLatitude() {
        return latitude_;
      }
      /**
       * <code>double latitude = 1;</code>
       * @param value The latitude to set.
       * @return This builder for chaining.
       */
      public Builder setLatitude(double value) {
        
        latitude_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>double latitude = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearLatitude() {
        bitField0_ = (bitField0_ & ~0x00000001);
        latitude_ = 0D;
        onChanged();
        return this;
      }

      private double longitude_ ;
      /**
       * <code>double longitude = 2;</code>
       * @return The longitude.
       */
      @Override
      public double getLongitude() {
        return longitude_;
      }
      /**
       * <code>double longitude = 2;</code>
       * @param value The longitude to set.
       * @return This builder for chaining.
       */
      public Builder setLongitude(double value) {
        
        longitude_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>double longitude = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearLongitude() {
        bitField0_ = (bitField0_ & ~0x00000002);
        longitude_ = 0D;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Location)
    }

    // @@protoc_insertion_point(class_scope:Location)
    private static final Location DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Location();
    }

    public static Location getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Location>
        PARSER = new com.google.protobuf.AbstractParser<Location>() {
      @Override
      public Location parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Location> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Location> getParserForType() {
      return PARSER;
    }

    @Override
    public Location getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ComplexPublication_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ComplexPublication_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Location_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Location_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\030ComplexPublication.proto\"\212\001\n\022ComplexPu" +
      "blication\022\014\n\004uuid\030\001 \001(\t\022\014\n\004city\030\002 \001(\t\022\033\n" +
      "\010location\030\003 \001(\0132\t.Location\022\027\n\017avg_temper" +
      "ature\030\004 \001(\001\022\020\n\010avg_rain\030\005 \001(\001\022\020\n\010avg_win" +
      "d\030\006 \001(\001\"/\n\010Location\022\020\n\010latitude\030\001 \001(\001\022\021\n" +
      "\tlongitude\030\002 \001(\001B-\n\022org.project.modelsB\027" +
      "ProtoComplexPublicationb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ComplexPublication_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ComplexPublication_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ComplexPublication_descriptor,
        new String[] { "Uuid", "City", "Location", "AvgTemperature", "AvgRain", "AvgWind", });
    internal_static_Location_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Location_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Location_descriptor,
        new String[] { "Latitude", "Longitude", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
