// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SimplePublication.proto

package org.project.models;

public final class ProtoSimplePublication {
  private ProtoSimplePublication() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SimplePublicationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SimplePublication)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string station_id = 1;</code>
     * @return The stationId.
     */
    java.lang.String getStationId();
    /**
     * <code>string station_id = 1;</code>
     * @return The bytes for stationId.
     */
    com.google.protobuf.ByteString
        getStationIdBytes();

    /**
     * <code>.Location location = 2;</code>
     * @return Whether the location field is set.
     */
    boolean hasLocation();
    /**
     * <code>.Location location = 2;</code>
     * @return The location.
     */
    org.project.models.ProtoSimplePublication.Location getLocation();
    /**
     * <code>.Location location = 2;</code>
     */
    org.project.models.ProtoSimplePublication.LocationOrBuilder getLocationOrBuilder();

    /**
     * <code>string city = 3;</code>
     * @return The city.
     */
    java.lang.String getCity();
    /**
     * <code>string city = 3;</code>
     * @return The bytes for city.
     */
    com.google.protobuf.ByteString
        getCityBytes();

    /**
     * <code>double temperature = 4;</code>
     * @return The temperature.
     */
    double getTemperature();

    /**
     * <code>double rain = 5;</code>
     * @return The rain.
     */
    double getRain();

    /**
     * <code>double wind = 6;</code>
     * @return The wind.
     */
    double getWind();

    /**
     * <code>string direction = 7;</code>
     * @return The direction.
     */
    java.lang.String getDirection();
    /**
     * <code>string direction = 7;</code>
     * @return The bytes for direction.
     */
    com.google.protobuf.ByteString
        getDirectionBytes();

    /**
     * <code>string date = 8;</code>
     * @return The date.
     */
    java.lang.String getDate();
    /**
     * <code>string date = 8;</code>
     * @return The bytes for date.
     */
    com.google.protobuf.ByteString
        getDateBytes();
  }
  /**
   * Protobuf type {@code SimplePublication}
   */
  public static final class SimplePublication extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:SimplePublication)
      SimplePublicationOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SimplePublication.newBuilder() to construct.
    private SimplePublication(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SimplePublication() {
      stationId_ = "";
      city_ = "";
      direction_ = "";
      date_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SimplePublication();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return internal_static_SimplePublication_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return internal_static_SimplePublication_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.project.models.ProtoSimplePublication.SimplePublication.class, org.project.models.ProtoSimplePublication.SimplePublication.Builder.class);
    }

    public static final int STATION_ID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object stationId_ = "";
    /**
     * <code>string station_id = 1;</code>
     * @return The stationId.
     */
    @java.lang.Override
    public java.lang.String getStationId() {
      java.lang.Object ref = stationId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        stationId_ = s;
        return s;
      }
    }
    /**
     * <code>string station_id = 1;</code>
     * @return The bytes for stationId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getStationIdBytes() {
      java.lang.Object ref = stationId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stationId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LOCATION_FIELD_NUMBER = 2;
    private org.project.models.ProtoSimplePublication.Location location_;
    /**
     * <code>.Location location = 2;</code>
     * @return Whether the location field is set.
     */
    @java.lang.Override
    public boolean hasLocation() {
      return location_ != null;
    }
    /**
     * <code>.Location location = 2;</code>
     * @return The location.
     */
    @java.lang.Override
    public org.project.models.ProtoSimplePublication.Location getLocation() {
      return location_ == null ? org.project.models.ProtoSimplePublication.Location.getDefaultInstance() : location_;
    }
    /**
     * <code>.Location location = 2;</code>
     */
    @java.lang.Override
    public org.project.models.ProtoSimplePublication.LocationOrBuilder getLocationOrBuilder() {
      return location_ == null ? org.project.models.ProtoSimplePublication.Location.getDefaultInstance() : location_;
    }

    public static final int CITY_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object city_ = "";
    /**
     * <code>string city = 3;</code>
     * @return The city.
     */
    @java.lang.Override
    public java.lang.String getCity() {
      java.lang.Object ref = city_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        city_ = s;
        return s;
      }
    }
    /**
     * <code>string city = 3;</code>
     * @return The bytes for city.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCityBytes() {
      java.lang.Object ref = city_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        city_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TEMPERATURE_FIELD_NUMBER = 4;
    private double temperature_ = 0D;
    /**
     * <code>double temperature = 4;</code>
     * @return The temperature.
     */
    @java.lang.Override
    public double getTemperature() {
      return temperature_;
    }

    public static final int RAIN_FIELD_NUMBER = 5;
    private double rain_ = 0D;
    /**
     * <code>double rain = 5;</code>
     * @return The rain.
     */
    @java.lang.Override
    public double getRain() {
      return rain_;
    }

    public static final int WIND_FIELD_NUMBER = 6;
    private double wind_ = 0D;
    /**
     * <code>double wind = 6;</code>
     * @return The wind.
     */
    @java.lang.Override
    public double getWind() {
      return wind_;
    }

    public static final int DIRECTION_FIELD_NUMBER = 7;
    @SuppressWarnings("serial")
    private volatile java.lang.Object direction_ = "";
    /**
     * <code>string direction = 7;</code>
     * @return The direction.
     */
    @java.lang.Override
    public java.lang.String getDirection() {
      java.lang.Object ref = direction_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        direction_ = s;
        return s;
      }
    }
    /**
     * <code>string direction = 7;</code>
     * @return The bytes for direction.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDirectionBytes() {
      java.lang.Object ref = direction_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        direction_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATE_FIELD_NUMBER = 8;
    @SuppressWarnings("serial")
    private volatile java.lang.Object date_ = "";
    /**
     * <code>string date = 8;</code>
     * @return The date.
     */
    @java.lang.Override
    public java.lang.String getDate() {
      java.lang.Object ref = date_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        date_ = s;
        return s;
      }
    }
    /**
     * <code>string date = 8;</code>
     * @return The bytes for date.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDateBytes() {
      java.lang.Object ref = date_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        date_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(stationId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, stationId_);
      }
      if (location_ != null) {
        output.writeMessage(2, getLocation());
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(city_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, city_);
      }
      if (java.lang.Double.doubleToRawLongBits(temperature_) != 0) {
        output.writeDouble(4, temperature_);
      }
      if (java.lang.Double.doubleToRawLongBits(rain_) != 0) {
        output.writeDouble(5, rain_);
      }
      if (java.lang.Double.doubleToRawLongBits(wind_) != 0) {
        output.writeDouble(6, wind_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(direction_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, direction_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(date_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, date_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(stationId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, stationId_);
      }
      if (location_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getLocation());
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(city_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, city_);
      }
      if (java.lang.Double.doubleToRawLongBits(temperature_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, temperature_);
      }
      if (java.lang.Double.doubleToRawLongBits(rain_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(5, rain_);
      }
      if (java.lang.Double.doubleToRawLongBits(wind_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(6, wind_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(direction_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, direction_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(date_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, date_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.project.models.ProtoSimplePublication.SimplePublication)) {
        return super.equals(obj);
      }
      org.project.models.ProtoSimplePublication.SimplePublication other = (org.project.models.ProtoSimplePublication.SimplePublication) obj;

      if (!getStationId()
          .equals(other.getStationId())) return false;
      if (hasLocation() != other.hasLocation()) return false;
      if (hasLocation()) {
        if (!getLocation()
            .equals(other.getLocation())) return false;
      }
      if (!getCity()
          .equals(other.getCity())) return false;
      if (java.lang.Double.doubleToLongBits(getTemperature())
          != java.lang.Double.doubleToLongBits(
              other.getTemperature())) return false;
      if (java.lang.Double.doubleToLongBits(getRain())
          != java.lang.Double.doubleToLongBits(
              other.getRain())) return false;
      if (java.lang.Double.doubleToLongBits(getWind())
          != java.lang.Double.doubleToLongBits(
              other.getWind())) return false;
      if (!getDirection()
          .equals(other.getDirection())) return false;
      if (!getDate()
          .equals(other.getDate())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STATION_ID_FIELD_NUMBER;
      hash = (53 * hash) + getStationId().hashCode();
      if (hasLocation()) {
        hash = (37 * hash) + LOCATION_FIELD_NUMBER;
        hash = (53 * hash) + getLocation().hashCode();
      }
      hash = (37 * hash) + CITY_FIELD_NUMBER;
      hash = (53 * hash) + getCity().hashCode();
      hash = (37 * hash) + TEMPERATURE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getTemperature()));
      hash = (37 * hash) + RAIN_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getRain()));
      hash = (37 * hash) + WIND_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getWind()));
      hash = (37 * hash) + DIRECTION_FIELD_NUMBER;
      hash = (53 * hash) + getDirection().hashCode();
      hash = (37 * hash) + DATE_FIELD_NUMBER;
      hash = (53 * hash) + getDate().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.project.models.ProtoSimplePublication.SimplePublication parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.project.models.ProtoSimplePublication.SimplePublication parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.project.models.ProtoSimplePublication.SimplePublication parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.project.models.ProtoSimplePublication.SimplePublication parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.project.models.ProtoSimplePublication.SimplePublication parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.project.models.ProtoSimplePublication.SimplePublication parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.project.models.ProtoSimplePublication.SimplePublication parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.project.models.ProtoSimplePublication.SimplePublication parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.project.models.ProtoSimplePublication.SimplePublication parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.project.models.ProtoSimplePublication.SimplePublication parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.project.models.ProtoSimplePublication.SimplePublication parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.project.models.ProtoSimplePublication.SimplePublication parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.project.models.ProtoSimplePublication.SimplePublication prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SimplePublication}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SimplePublication)
        org.project.models.ProtoSimplePublication.SimplePublicationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return internal_static_SimplePublication_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return internal_static_SimplePublication_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.project.models.ProtoSimplePublication.SimplePublication.class, org.project.models.ProtoSimplePublication.SimplePublication.Builder.class);
      }

      // Construct using org.project.models.ProtoSimplePublication.SimplePublication.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        stationId_ = "";
        location_ = null;
        if (locationBuilder_ != null) {
          locationBuilder_.dispose();
          locationBuilder_ = null;
        }
        city_ = "";
        temperature_ = 0D;
        rain_ = 0D;
        wind_ = 0D;
        direction_ = "";
        date_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return internal_static_SimplePublication_descriptor;
      }

      @java.lang.Override
      public org.project.models.ProtoSimplePublication.SimplePublication getDefaultInstanceForType() {
        return getDefaultInstance();
      }

      @java.lang.Override
      public org.project.models.ProtoSimplePublication.SimplePublication build() {
        org.project.models.ProtoSimplePublication.SimplePublication result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.project.models.ProtoSimplePublication.SimplePublication buildPartial() {
        org.project.models.ProtoSimplePublication.SimplePublication result = new org.project.models.ProtoSimplePublication.SimplePublication(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(org.project.models.ProtoSimplePublication.SimplePublication result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.stationId_ = stationId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.location_ = locationBuilder_ == null
              ? location_
              : locationBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.city_ = city_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.temperature_ = temperature_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.rain_ = rain_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.wind_ = wind_;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.direction_ = direction_;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.date_ = date_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.project.models.ProtoSimplePublication.SimplePublication) {
          return mergeFrom((org.project.models.ProtoSimplePublication.SimplePublication)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.project.models.ProtoSimplePublication.SimplePublication other) {
        if (other == getDefaultInstance()) return this;
        if (!other.getStationId().isEmpty()) {
          stationId_ = other.stationId_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.hasLocation()) {
          mergeLocation(other.getLocation());
        }
        if (!other.getCity().isEmpty()) {
          city_ = other.city_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (other.getTemperature() != 0D) {
          setTemperature(other.getTemperature());
        }
        if (other.getRain() != 0D) {
          setRain(other.getRain());
        }
        if (other.getWind() != 0D) {
          setWind(other.getWind());
        }
        if (!other.getDirection().isEmpty()) {
          direction_ = other.direction_;
          bitField0_ |= 0x00000040;
          onChanged();
        }
        if (!other.getDate().isEmpty()) {
          date_ = other.date_;
          bitField0_ |= 0x00000080;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                stationId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                input.readMessage(
                    getLocationFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                city_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 33: {
                temperature_ = input.readDouble();
                bitField0_ |= 0x00000008;
                break;
              } // case 33
              case 41: {
                rain_ = input.readDouble();
                bitField0_ |= 0x00000010;
                break;
              } // case 41
              case 49: {
                wind_ = input.readDouble();
                bitField0_ |= 0x00000020;
                break;
              } // case 49
              case 58: {
                direction_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000040;
                break;
              } // case 58
              case 66: {
                date_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000080;
                break;
              } // case 66
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object stationId_ = "";
      /**
       * <code>string station_id = 1;</code>
       * @return The stationId.
       */
      public java.lang.String getStationId() {
        java.lang.Object ref = stationId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          stationId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string station_id = 1;</code>
       * @return The bytes for stationId.
       */
      public com.google.protobuf.ByteString
          getStationIdBytes() {
        java.lang.Object ref = stationId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          stationId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string station_id = 1;</code>
       * @param value The stationId to set.
       * @return This builder for chaining.
       */
      public Builder setStationId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        stationId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string station_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearStationId() {
        stationId_ = getDefaultInstance().getStationId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string station_id = 1;</code>
       * @param value The bytes for stationId to set.
       * @return This builder for chaining.
       */
      public Builder setStationIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        stationId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private org.project.models.ProtoSimplePublication.Location location_;
      private com.google.protobuf.SingleFieldBuilderV3<
          org.project.models.ProtoSimplePublication.Location, org.project.models.ProtoSimplePublication.Location.Builder, org.project.models.ProtoSimplePublication.LocationOrBuilder> locationBuilder_;
      /**
       * <code>.Location location = 2;</code>
       * @return Whether the location field is set.
       */
      public boolean hasLocation() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>.Location location = 2;</code>
       * @return The location.
       */
      public org.project.models.ProtoSimplePublication.Location getLocation() {
        if (locationBuilder_ == null) {
          return location_ == null ? org.project.models.ProtoSimplePublication.Location.getDefaultInstance() : location_;
        } else {
          return locationBuilder_.getMessage();
        }
      }
      /**
       * <code>.Location location = 2;</code>
       */
      public Builder setLocation(org.project.models.ProtoSimplePublication.Location value) {
        if (locationBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          location_ = value;
        } else {
          locationBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.Location location = 2;</code>
       */
      public Builder setLocation(
          org.project.models.ProtoSimplePublication.Location.Builder builderForValue) {
        if (locationBuilder_ == null) {
          location_ = builderForValue.build();
        } else {
          locationBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.Location location = 2;</code>
       */
      public Builder mergeLocation(org.project.models.ProtoSimplePublication.Location value) {
        if (locationBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
            location_ != null &&
            location_ != org.project.models.ProtoSimplePublication.Location.getDefaultInstance()) {
            getLocationBuilder().mergeFrom(value);
          } else {
            location_ = value;
          }
        } else {
          locationBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.Location location = 2;</code>
       */
      public Builder clearLocation() {
        bitField0_ = (bitField0_ & ~0x00000002);
        location_ = null;
        if (locationBuilder_ != null) {
          locationBuilder_.dispose();
          locationBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.Location location = 2;</code>
       */
      public org.project.models.ProtoSimplePublication.Location.Builder getLocationBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getLocationFieldBuilder().getBuilder();
      }
      /**
       * <code>.Location location = 2;</code>
       */
      public org.project.models.ProtoSimplePublication.LocationOrBuilder getLocationOrBuilder() {
        if (locationBuilder_ != null) {
          return locationBuilder_.getMessageOrBuilder();
        } else {
          return location_ == null ?
              org.project.models.ProtoSimplePublication.Location.getDefaultInstance() : location_;
        }
      }
      /**
       * <code>.Location location = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          org.project.models.ProtoSimplePublication.Location, org.project.models.ProtoSimplePublication.Location.Builder, org.project.models.ProtoSimplePublication.LocationOrBuilder> 
          getLocationFieldBuilder() {
        if (locationBuilder_ == null) {
          locationBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              org.project.models.ProtoSimplePublication.Location, org.project.models.ProtoSimplePublication.Location.Builder, org.project.models.ProtoSimplePublication.LocationOrBuilder>(
                  getLocation(),
                  getParentForChildren(),
                  isClean());
          location_ = null;
        }
        return locationBuilder_;
      }

      private java.lang.Object city_ = "";
      /**
       * <code>string city = 3;</code>
       * @return The city.
       */
      public java.lang.String getCity() {
        java.lang.Object ref = city_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          city_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string city = 3;</code>
       * @return The bytes for city.
       */
      public com.google.protobuf.ByteString
          getCityBytes() {
        java.lang.Object ref = city_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          city_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string city = 3;</code>
       * @param value The city to set.
       * @return This builder for chaining.
       */
      public Builder setCity(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        city_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string city = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearCity() {
        city_ = getDefaultInstance().getCity();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string city = 3;</code>
       * @param value The bytes for city to set.
       * @return This builder for chaining.
       */
      public Builder setCityBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        city_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private double temperature_ ;
      /**
       * <code>double temperature = 4;</code>
       * @return The temperature.
       */
      @java.lang.Override
      public double getTemperature() {
        return temperature_;
      }
      /**
       * <code>double temperature = 4;</code>
       * @param value The temperature to set.
       * @return This builder for chaining.
       */
      public Builder setTemperature(double value) {
        
        temperature_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>double temperature = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearTemperature() {
        bitField0_ = (bitField0_ & ~0x00000008);
        temperature_ = 0D;
        onChanged();
        return this;
      }

      private double rain_ ;
      /**
       * <code>double rain = 5;</code>
       * @return The rain.
       */
      @java.lang.Override
      public double getRain() {
        return rain_;
      }
      /**
       * <code>double rain = 5;</code>
       * @param value The rain to set.
       * @return This builder for chaining.
       */
      public Builder setRain(double value) {
        
        rain_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>double rain = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearRain() {
        bitField0_ = (bitField0_ & ~0x00000010);
        rain_ = 0D;
        onChanged();
        return this;
      }

      private double wind_ ;
      /**
       * <code>double wind = 6;</code>
       * @return The wind.
       */
      @java.lang.Override
      public double getWind() {
        return wind_;
      }
      /**
       * <code>double wind = 6;</code>
       * @param value The wind to set.
       * @return This builder for chaining.
       */
      public Builder setWind(double value) {
        
        wind_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>double wind = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearWind() {
        bitField0_ = (bitField0_ & ~0x00000020);
        wind_ = 0D;
        onChanged();
        return this;
      }

      private java.lang.Object direction_ = "";
      /**
       * <code>string direction = 7;</code>
       * @return The direction.
       */
      public java.lang.String getDirection() {
        java.lang.Object ref = direction_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          direction_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string direction = 7;</code>
       * @return The bytes for direction.
       */
      public com.google.protobuf.ByteString
          getDirectionBytes() {
        java.lang.Object ref = direction_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          direction_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string direction = 7;</code>
       * @param value The direction to set.
       * @return This builder for chaining.
       */
      public Builder setDirection(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        direction_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>string direction = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearDirection() {
        direction_ = getDefaultInstance().getDirection();
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
        return this;
      }
      /**
       * <code>string direction = 7;</code>
       * @param value The bytes for direction to set.
       * @return This builder for chaining.
       */
      public Builder setDirectionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        direction_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }

      private java.lang.Object date_ = "";
      /**
       * <code>string date = 8;</code>
       * @return The date.
       */
      public java.lang.String getDate() {
        java.lang.Object ref = date_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          date_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string date = 8;</code>
       * @return The bytes for date.
       */
      public com.google.protobuf.ByteString
          getDateBytes() {
        java.lang.Object ref = date_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          date_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string date = 8;</code>
       * @param value The date to set.
       * @return This builder for chaining.
       */
      public Builder setDate(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        date_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <code>string date = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearDate() {
        date_ = getDefaultInstance().getDate();
        bitField0_ = (bitField0_ & ~0x00000080);
        onChanged();
        return this;
      }
      /**
       * <code>string date = 8;</code>
       * @param value The bytes for date to set.
       * @return This builder for chaining.
       */
      public Builder setDateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        date_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:SimplePublication)
    }

    // @@protoc_insertion_point(class_scope:SimplePublication)
    private static final org.project.models.ProtoSimplePublication.SimplePublication DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.project.models.ProtoSimplePublication.SimplePublication();
    }

    public static org.project.models.ProtoSimplePublication.SimplePublication getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SimplePublication>
        PARSER = new com.google.protobuf.AbstractParser<SimplePublication>() {
      @java.lang.Override
      public SimplePublication parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<SimplePublication> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SimplePublication> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.project.models.ProtoSimplePublication.SimplePublication getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface LocationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Location)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>double latitude = 1;</code>
     * @return The latitude.
     */
    double getLatitude();

    /**
     * <code>double longitude = 2;</code>
     * @return The longitude.
     */
    double getLongitude();
  }
  /**
   * Protobuf type {@code Location}
   */
  public static final class Location extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Location)
      LocationOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Location.newBuilder() to construct.
    private Location(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Location() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Location();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return internal_static_Location_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return internal_static_Location_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.project.models.ProtoSimplePublication.Location.class, org.project.models.ProtoSimplePublication.Location.Builder.class);
    }

    public static final int LATITUDE_FIELD_NUMBER = 1;
    private double latitude_ = 0D;
    /**
     * <code>double latitude = 1;</code>
     * @return The latitude.
     */
    @java.lang.Override
    public double getLatitude() {
      return latitude_;
    }

    public static final int LONGITUDE_FIELD_NUMBER = 2;
    private double longitude_ = 0D;
    /**
     * <code>double longitude = 2;</code>
     * @return The longitude.
     */
    @java.lang.Override
    public double getLongitude() {
      return longitude_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (java.lang.Double.doubleToRawLongBits(latitude_) != 0) {
        output.writeDouble(1, latitude_);
      }
      if (java.lang.Double.doubleToRawLongBits(longitude_) != 0) {
        output.writeDouble(2, longitude_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (java.lang.Double.doubleToRawLongBits(latitude_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, latitude_);
      }
      if (java.lang.Double.doubleToRawLongBits(longitude_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, longitude_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.project.models.ProtoSimplePublication.Location)) {
        return super.equals(obj);
      }
      org.project.models.ProtoSimplePublication.Location other = (org.project.models.ProtoSimplePublication.Location) obj;

      if (java.lang.Double.doubleToLongBits(getLatitude())
          != java.lang.Double.doubleToLongBits(
              other.getLatitude())) return false;
      if (java.lang.Double.doubleToLongBits(getLongitude())
          != java.lang.Double.doubleToLongBits(
              other.getLongitude())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + LATITUDE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getLatitude()));
      hash = (37 * hash) + LONGITUDE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getLongitude()));
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.project.models.ProtoSimplePublication.Location parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.project.models.ProtoSimplePublication.Location parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.project.models.ProtoSimplePublication.Location parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.project.models.ProtoSimplePublication.Location parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.project.models.ProtoSimplePublication.Location parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.project.models.ProtoSimplePublication.Location parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.project.models.ProtoSimplePublication.Location parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.project.models.ProtoSimplePublication.Location parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.project.models.ProtoSimplePublication.Location parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.project.models.ProtoSimplePublication.Location parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.project.models.ProtoSimplePublication.Location parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.project.models.ProtoSimplePublication.Location parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.project.models.ProtoSimplePublication.Location prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Location}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Location)
        org.project.models.ProtoSimplePublication.LocationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return internal_static_Location_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return internal_static_Location_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.project.models.ProtoSimplePublication.Location.class, org.project.models.ProtoSimplePublication.Location.Builder.class);
      }

      // Construct using org.project.models.ProtoSimplePublication.Location.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        latitude_ = 0D;
        longitude_ = 0D;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return internal_static_Location_descriptor;
      }

      @java.lang.Override
      public org.project.models.ProtoSimplePublication.Location getDefaultInstanceForType() {
        return getDefaultInstance();
      }

      @java.lang.Override
      public org.project.models.ProtoSimplePublication.Location build() {
        org.project.models.ProtoSimplePublication.Location result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.project.models.ProtoSimplePublication.Location buildPartial() {
        org.project.models.ProtoSimplePublication.Location result = new org.project.models.ProtoSimplePublication.Location(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(org.project.models.ProtoSimplePublication.Location result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.latitude_ = latitude_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.longitude_ = longitude_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.project.models.ProtoSimplePublication.Location) {
          return mergeFrom((org.project.models.ProtoSimplePublication.Location)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.project.models.ProtoSimplePublication.Location other) {
        if (other == getDefaultInstance()) return this;
        if (other.getLatitude() != 0D) {
          setLatitude(other.getLatitude());
        }
        if (other.getLongitude() != 0D) {
          setLongitude(other.getLongitude());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 9: {
                latitude_ = input.readDouble();
                bitField0_ |= 0x00000001;
                break;
              } // case 9
              case 17: {
                longitude_ = input.readDouble();
                bitField0_ |= 0x00000002;
                break;
              } // case 17
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private double latitude_ ;
      /**
       * <code>double latitude = 1;</code>
       * @return The latitude.
       */
      @java.lang.Override
      public double getLatitude() {
        return latitude_;
      }
      /**
       * <code>double latitude = 1;</code>
       * @param value The latitude to set.
       * @return This builder for chaining.
       */
      public Builder setLatitude(double value) {
        
        latitude_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>double latitude = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearLatitude() {
        bitField0_ = (bitField0_ & ~0x00000001);
        latitude_ = 0D;
        onChanged();
        return this;
      }

      private double longitude_ ;
      /**
       * <code>double longitude = 2;</code>
       * @return The longitude.
       */
      @java.lang.Override
      public double getLongitude() {
        return longitude_;
      }
      /**
       * <code>double longitude = 2;</code>
       * @param value The longitude to set.
       * @return This builder for chaining.
       */
      public Builder setLongitude(double value) {
        
        longitude_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>double longitude = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearLongitude() {
        bitField0_ = (bitField0_ & ~0x00000002);
        longitude_ = 0D;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Location)
    }

    // @@protoc_insertion_point(class_scope:Location)
    private static final org.project.models.ProtoSimplePublication.Location DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.project.models.ProtoSimplePublication.Location();
    }

    public static org.project.models.ProtoSimplePublication.Location getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Location>
        PARSER = new com.google.protobuf.AbstractParser<Location>() {
      @java.lang.Override
      public Location parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Location> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Location> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.project.models.ProtoSimplePublication.Location getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SimplePublication_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SimplePublication_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Location_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Location_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027SimplePublication.proto\"\244\001\n\021SimplePubl" +
      "ication\022\022\n\nstation_id\030\001 \001(\t\022\033\n\010location\030" +
      "\002 \001(\0132\t.Location\022\014\n\004city\030\003 \001(\t\022\023\n\013temper" +
      "ature\030\004 \001(\001\022\014\n\004rain\030\005 \001(\001\022\014\n\004wind\030\006 \001(\001\022" +
      "\021\n\tdirection\030\007 \001(\t\022\014\n\004date\030\010 \001(\t\"/\n\010Loca" +
      "tion\022\020\n\010latitude\030\001 \001(\001\022\021\n\tlongitude\030\002 \001(" +
      "\001B,\n\022org.project.modelsB\026ProtoSimplePubl" +
      "icationb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_SimplePublication_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SimplePublication_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SimplePublication_descriptor,
        new java.lang.String[] { "StationId", "Location", "City", "Temperature", "Rain", "Wind", "Direction", "Date", });
    internal_static_Location_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Location_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Location_descriptor,
        new java.lang.String[] { "Latitude", "Longitude", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
